<a href="https://colab.research.google.com/github/IO-2024/IOTs_with_python/blob/main/Ch_%EB%B6%80%EB%A1%9D_2.%EB%B6%80%EB%AC%B8%ED%86%B5%ED%95%A9_%EC%A0%84%EA%B5%ADIO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

In [2]:
np.set_printoptions(precision=3,suppress=True) # 결과를 소수 3자리까지만 보여주는 옵션

# 부문통합하여 3부문 IO표 만들기

- <전국산업연관표>
- 2019년 산업연관표(33부문)를 IO표를 3부문 IO표로 통합하고 이를 통해 설명
- 33부문을 3부문(농산품, 공산품, 서비스)으로 통합하기 위하여 행렬 곱을 사용
- 0과 1로 구성된 행렬을 만드는데 각 행은 새로운 표의 부문을 나타내며 각 열은 33부문의 부문을 나타냄

In [3]:
Code = np.array([[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],  # 행렬곱을 이용한 부문 통합을 위해 0과 1로 구성된 임시의 3x33 매트릭스
       [0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
       [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]])
print('코드매치를 위한 매트릭스', '\n', Code)

코드매치를 위한 매트릭스 
 [[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]


In [4]:
Cdd = "https://raw.githubusercontent.com/IO-2024/IOTs_with_python/main/data/code.csv"  # 코드매치 파일
Ccdd = pd.read_csv(Cdd)
Cd_for_itr = Ccdd.to_numpy().reshape(33,2)
Cd_3 = Cd_for_itr[:,1]
Cd_33 = Cd_for_itr[:,0]
print('3부문 코드 : \n', Cd_3)
print('33부문 코드 : \n', Cd_33)

3부문 코드 : 
 [1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
33부문 코드 : 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33]


In [5]:
Mtx = np.zeros((3,33)) # 수작업 대신 반복문을 통해 3x33 임시코드 만들기
Row=Cd_3
Col=Cd_33
for i, j in zip(Row,Col):
  Mtx[i-1,j-1] = 1
print('코드매치를 위한 매트릭스_불러오기후', '\n', Mtx)

코드매치를 위한 매트릭스_불러오기후 
 [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1.]]


##### - 직접 입력하든 미리 만들어 둔 파일을 이용하든 코드매치를 위한 매트릭스는 동일하며 이후 작업에는 Mtx를 사용

###  총거래표

In [6]:
url_Tt_33 = "https://raw.githubusercontent.com/IO-2024/IOTs_with_python/main/data/Total_Matrix.csv"  # 33부문의 총거래표 불러오기
Tt_33 = pd.read_csv(url_Tt_33)

In [7]:
Ttt_33 = Tt_33.to_numpy()
Tot_33 = Ttt_33[0:41,1:53].astype(float)

In [8]:
Nae_tot = Mtx@Tot_33[0:33,0:33]@Mtx.T # 내생(중간투입) 거래표
print('내생거래표', '\n', Nae_tot)

내생거래표 
 [[  4.  38.  11.]
 [ 16. 944. 401.]
 [  7. 257. 693.]]


In [9]:
Va_row = Tot_33[33:40,0:33]@Mtx.T # 중간투입계, 피용자보수, 영업잉여, 고정자본소모, 기타생산세, 부가가치계, 산출액(7X3)
Va_row

array([[  27., 1239., 1105.],
       [   7.,  197.,  714.],
       [  20.,  152.,  298.],
       [   5.,  144.,  230.],
       [   1.,   60.,  100.],
       [  33.,  553., 1342.],
       [  60., 1792., 2447.]])

In [10]:
Va_row.shape

(7, 3)

In [11]:
Fd_cd = np.array([[1,1,0,0,0,0,0,0,0],   # 최종수요를 통합하기 위한 0과 1로된 행렬(소비,투자,수출로 통합)
                  [0,0,1,1,1,1,0,0,0],
                  [0,0,0,0,0,0,1,0,0],
                  [0,0,0,0,0,0,0,1,0],
                  [0,0,0,0,0,0,0,0,1]])

In [12]:
Fd = Tot_33[0:33, 34:45]
Fd

array([[ 18.,   0.,   0.,   0.,   0.,   0.,   1.,  19.,  72.],
       [  0.,   0.,   0.,   0.,   2.,   0.,   0.,   2., 149.],
       [ 67.,   0.,   0.,   0.,   1.,   0.,   9.,  77., 168.],
       [ 35.,   0.,   0.,   0.,   1.,   0.,  24.,  60.,  97.],
       [  1.,   0.,   0.,   0.,   1.,   0.,   4.,   6.,  52.],
       [ 16.,   0.,   0.,   0.,   1.,   0.,  52.,  69., 165.],
       [ 11.,   0.,   0.,   0.,   6.,   0., 104., 121., 355.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   5.,   5.,  45.],
       [ -1.,   0.,  -3.,   0.,   1.,   0.,  44.,  41., 181.],
       [  2.,   0.,   3.,   4.,   1.,   0.,  12.,  22., 108.],
       [ 27.,   0.,  26.,   5.,   3.,   0., 173., 234., 383.],
       [  9.,   0.,  10.,   0.,   1.,   0.,  31.,  51., 128.],
       [  3.,   0.,  57.,   0.,  -1.,   0.,  60., 119., 175.],
       [ 33.,   0.,  29.,  11.,   2.,   0., 104., 179., 263.],
       [ 10.,   0.,   4.,   0.,   0.,   2.,   4.,  20.,  30.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   2.,   2.,

In [13]:

Fd_row=Code@Fd@Fd_cd.T
Fd_row


array([[  18.,    0.,    1.,   19.,   72.],
       [ 213.,  167.,  628., 1008., 2369.],
       [1032.,  432.,  131., 1595., 2552.]])

In [14]:

Fd_row_sm = np.sum((Fd_row), axis=0) # 최종수요의 행합
Fd_sm=Fd_row_sm.reshape(1,5)

In [15]:
Nae_va_ct = np.concatenate((Nae_tot, Va_row)) # 중간투입(수요)과 부가가치 및 산출액 합치기
Nae_va_ct

array([[   4.,   38.,   11.],
       [  16.,  944.,  401.],
       [   7.,  257.,  693.],
       [  27., 1239., 1105.],
       [   7.,  197.,  714.],
       [  20.,  152.,  298.],
       [   5.,  144.,  230.],
       [   1.,   60.,  100.],
       [  33.,  553., 1342.],
       [  60., 1792., 2447.]])

In [16]:
Nae_va_ct_sm = Nae_va_ct.sum(axis=1).reshape(10,1)  # 부가가치 및 산출액의 열합

In [17]:
Nnull = np.zeros((6,5)) # 0행렬

In [18]:
Fd_nnull = np.concatenate((Fd_row, Fd_sm, Nnull),axis=0)  # 최종수요, 최종수요의 행합 및 0행렬 합치기

In [19]:
Tot_f = np.concatenate((Nae_va_ct,Nae_va_ct_sm, Fd_nnull), axis=1)  # 최종 3x3 부문통합된 거래표(부가가치항목포함)
Tot_f_va1 = np.concatenate((Tot_f[0:4,], Tot_f[-2:,:]), axis=0)  # 최종 3x3 부문통합된 거래표(부가가치계만 포함)
print('3부문 총거래표', '\n', Tot_f_va1)

3부문 총거래표 
 [[   4.   38.   11.   53.   18.    0.    1.   19.   72.]
 [  16.  944.  401. 1361.  213.  167.  628. 1008. 2369.]
 [   7.  257.  693.  957. 1032.  432.  131. 1595. 2552.]
 [  27. 1239. 1105. 2371. 1263.  599.  760. 2622. 4993.]
 [  33.  553. 1342. 1928.    0.    0.    0.    0.    0.]
 [  60. 1792. 2447. 4299.    0.    0.    0.    0.    0.]]


In [20]:
Tot_F = pd.DataFrame(Tot_f, columns = ['농산품', '공산품', '서비스', '중간수요계', '소비','투자', '수출', '최종수요계', '총수요계'],
                     index=['농산품', '공산품', '서비스', '중간투입계', '피용자보수','영업잉여', '고정자본소모', '생산세(보조금공제)', '부가가치계', '총투입액']) # 변수명 붙여서 pandas로 내보내기

In [21]:
Tot_F_va1= pd.DataFrame(Tot_f_va1, columns = ['농산품', '공산품', '서비스', '중간수요계', '소비','투자', '수출', '최종수요계', '총수요계'],
                     index=['농산품', '공산품', '서비스', '중간투입계', '부가가치계', '총투입액']) # 변수명 붙여서 pandas로 내보내기

In [22]:
Tot_F_va1  #최종 3x3 거래표 확인

농산품     공산품     서비스   중간수요계      소비     투자     수출   최종수요계    총수요계
농산품     4.0    38.0    11.0    53.0    18.0    0.0    1.0    19.0    72.0
공산품    16.0   944.0   401.0  1361.0   213.0  167.0  628.0  1008.0  2369.0
서비스     7.0   257.0   693.0   957.0  1032.0  432.0  131.0  1595.0  2552.0
중간투입계  27.0  1239.0  1105.0  2371.0  1263.0  599.0  760.0  2622.0  4993.0
부가가치계  33.0   553.0  1342.0  1928.0     0.0    0.0    0.0     0.0     0.0
총투입액   60.0  1792.0  2447.0  4299.0     0.0    0.0    0.0     0.0     0.0

###  국산거래표

In [23]:
url_Dm_33 = "https://raw.githubusercontent.com/IO-2024/IOTs_with_python/main/data/Domestic_Matrix.csv"  # 33부문의 국산거래표 불러오기
Dm_33 = pd.read_csv(url_Dm_33)

In [24]:
Dmm_33 = Dm_33.to_numpy()
Dom_33 = Dmm_33[0:34,1:53].astype(float)

In [25]:
Nae_dom = (Mtx@Dom_33[0:33,0:33])@Mtx.T # 중간투입(수요)의 행을 3부문으로 만들기
Nae_dom

array([[  4.,  31.,  10.],
       [ 15., 588., 322.],
       [  7., 243., 644.]])

In [26]:
Dsm_row = Dom_33[33:34,0:33]@Mtx.T # 중간투입계
Dsm_row

array([[ 26., 862., 976.]])

In [27]:
Dfd = Dom_33[0:33, 34:45]
Dfd

array([[ 15.,   0.,   0.,   0.,  -1.,   0.,   1.,  15.,  60.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   3.],
       [ 52.,   0.,   0.,   0.,   1.,   0.,   9.,  62., 135.],
       [ 16.,   0.,   0.,   0.,   1.,   0.,  23.,  40.,  66.],
       [  1.,   0.,   0.,   0.,   1.,   0.,   4.,   6.,  46.],
       [ 15.,   0.,   0.,   0.,   1.,   0.,  52.,  68., 136.],
       [  3.,   0.,   0.,   0.,   5.,   0., 101., 109., 279.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   5.,   5.,  40.],
       [ -1.,   0.,  -3.,   0.,   1.,   0.,  44.,  41., 141.],
       [  1.,   0.,   3.,   3.,   1.,   0.,  12.,  20., 101.],
       [ 15.,   0.,  10.,   2.,   2.,   0., 172., 201., 285.],
       [  6.,   0.,   8.,   0.,   1.,   0.,  31.,  46., 108.],
       [  2.,   0.,  37.,   0.,  -1.,   0.,  60.,  98., 138.],
       [ 24.,   0.,  19.,   8.,   2.,   0., 104., 157., 233.],
       [  4.,   0.,   3.,   0.,   0.,   1.,   4.,  12.,  21.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   2.,   2.,

In [28]:
Dfd_row=Mtx@Dfd@Fd_cd.T

In [29]:
Dfd_row_sm = np.sum((Dfd_row), axis=0) # 최종수요의 행합

In [30]:
Dfd_sm=Dfd_row_sm.reshape(1,5)
Dfd_sm

array([[1150.,  530.,  755., 2435., 4299.]])

In [31]:
Nae_dm = np.concatenate((Nae_dom, Dsm_row)) # 중간투입과 중투입계 합치기
Nae_dm

array([[  4.,  31.,  10.],
       [ 15., 588., 322.],
       [  7., 243., 644.],
       [ 26., 862., 976.]])

In [32]:
Nae_col_sm_dm = Nae_dm.sum(axis=1).reshape(4,1)  # 중간투입(수요)과 행합

In [33]:
Nae_dm_sm = Nae_col_sm_dm.sum(axis=1).reshape(4,1)  # 중간수요와 중간수요계 합치기

In [34]:
Dfd_nnull = np.concatenate((Dfd_row, Dfd_sm),axis=0)  #   최종수요 및 최종수요계 합치기

In [35]:
Dom_f = np.concatenate((Nae_dm, Nae_dm_sm, Dfd_nnull), axis=1)  # 최종 3x3 부문통합된 거래표
print('3부문 국산거래표', '\n', Dom_f)

3부문 국산거래표 
 [[   4.   31.   10.   45.   15.   -1.    1.   15.   60.]
 [  15.  588.  322.  925.  138.  106.  623.  867. 1792.]
 [   7.  243.  644.  894.  997.  425.  131. 1553. 2447.]
 [  26.  862.  976. 1864. 1150.  530.  755. 2435. 4299.]]


In [36]:
dom_F = pd.DataFrame(Dom_f, columns = ['농산품', '공산품', '서비스', '중간수요계', '소비','투자', '수출', '최종수요계', '총수요계'],
                     index=['농산품', '공산품', '서비스', '중간투입계']) # 변수명 붙여서 pandas로 내보내기
dom_F

농산품    공산품    서비스   중간수요계      소비     투자     수출   최종수요계    총수요계
농산품     4.0   31.0   10.0    45.0    15.0   -1.0    1.0    15.0    60.0
공산품    15.0  588.0  322.0   925.0   138.0  106.0  623.0   867.0  1792.0
서비스     7.0  243.0  644.0   894.0   997.0  425.0  131.0  1553.0  2447.0
중간투입계  26.0  862.0  976.0  1864.0  1150.0  530.0  755.0  2435.0  4299.0

In [37]:
# dom_F.reset_index(inplace=True)# 인덱스 설정(부문명)
# dom_F

### 수입거래표

In [38]:

url_Im_33 = "https://raw.githubusercontent.com/IO-2024/IOTs_with_python/main/data/Imported_Matrix.csv"  # 33부문의 수입거래표 불러오기
Im_33 = pd.read_csv(url_Im_33)

In [39]:
Imm_33 = Im_33.to_numpy()
Imp_33 = Imm_33[0:34,1:53].astype(float)

In [40]:
Nae_imp = (Mtx@Imp_33[0:33,0:33])@Mtx.T # 중간투입(수요)의 행을 3부문으로 만들기
Nae_imp

array([[  0.,   7.,   1.],
       [  1., 356.,  79.],
       [  0.,  14.,  49.]])

In [41]:
Ism_row = Imp_33[33:34,0:33]@Mtx.T # 중간투입계
Ism_row


array([[  1., 377., 129.]])

In [42]:
Ifd = Imp_33[0:33, 34:45] #수입최종수요
Ifd

array([[  3.,   0.,   0.,   0.,   1.,   0.,   0.,   4.,  12.],
       [  0.,   0.,   0.,   0.,   2.,   0.,   0.,   2., 146.],
       [ 15.,   0.,   0.,   0.,   0.,   0.,   0.,  15.,  33.],
       [ 19.,   0.,   0.,   0.,   0.,   0.,   1.,  20.,  31.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   6.],
       [  1.,   0.,   0.,   0.,   0.,   0.,   0.,   1.,  29.],
       [  8.,   0.,   0.,   0.,   1.,   0.,   3.,  12.,  76.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   5.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  40.],
       [  1.,   0.,   0.,   1.,   0.,   0.,   0.,   2.,   7.],
       [ 12.,   0.,  16.,   3.,   1.,   0.,   1.,  33.,  98.],
       [  3.,   0.,   2.,   0.,   0.,   0.,   0.,   5.,  20.],
       [  1.,   0.,  20.,   0.,   0.,   0.,   0.,  21.,  37.],
       [  9.,   0.,  10.,   3.,   0.,   0.,   0.,  22.,  30.],
       [  6.,   0.,   1.,   0.,   0.,   1.,   0.,   8.,   9.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,

In [43]:
Ifd_row = Mtx@Ifd@Fd_cd.T

In [44]:
Ifd_row_sm = np.sum((Ifd_row), axis=0) # 최종수요의 행합

In [45]:
Ifd_sm=Ifd_row_sm.reshape(1,5)
Ifd_sm

array([[113.,  69.,   5., 187., 694.]])

In [46]:
Nae_im = np.concatenate((Nae_imp, Ism_row)) # 중간투입과 중간투입계 합치기
Nae_im

array([[  0.,   7.,   1.],
       [  1., 356.,  79.],
       [  0.,  14.,  49.],
       [  1., 377., 129.]])

In [47]:
Nae_col_sm_imp = Nae_im.sum(axis=1).reshape(4,1)  # 중간투입(수요)과 행합

In [48]:
Nae_im_sm = Nae_col_sm_imp.sum(axis=1).reshape(4,1)  # 중간수요와 중간수요계 합치기

In [49]:
Ifd_nnull = np.concatenate((Ifd_row, Ifd_sm),axis=0)  # 최종수요 및 최종수요계 합치기

In [50]:
Imp_f = np.concatenate((Nae_im, Nae_im_sm, Ifd_nnull), axis=1)  # 최종 3x3 부문통합된 거래표
print('3부문 수입거래표', '\n', Imp_f)

3부문 수입거래표 
 [[  0.   7.   1.   8.   3.   1.   0.   4.  12.]
 [  1. 356.  79. 436.  75.  61.   5. 141. 577.]
 [  0.  14.  49.  63.  35.   7.   0.  42. 105.]
 [  1. 377. 129. 507. 113.  69.   5. 187. 694.]]


In [51]:
Imp_f = pd.DataFrame(Imp_f, columns = ['농산품', '공산품', '서비스', '중간수요계', '소비','투자', '수출', '최종수요계', '총수요계'],
                     index=['농산품', '공산품', '서비스', '중간투입계']) # 변수명 붙여서 pandas로 내보내기
Imp_f

농산품    공산품    서비스  중간수요계     소비    투자   수출  최종수요계   총수요계
농산품    0.0    7.0    1.0    8.0    3.0   1.0  0.0    4.0   12.0
공산품    1.0  356.0   79.0  436.0   75.0  61.0  5.0  141.0  577.0
서비스    0.0   14.0   49.0   63.0   35.0   7.0  0.0   42.0  105.0
중간투입계  1.0  377.0  129.0  507.0  113.0  69.0  5.0  187.0  694.0